[core]
name: beamControlCenter
displayText: Orbital Beam Control Center
price: 20000
displayDescription: -Sets the plot point for the orbital beams
buildSpeed: 45s
maxHp: 1000
class: CustomUnitMetadata
mass: 9000

techLevel: 2
radius: 50

builtFrom_1_name: combatEngineer, experimentalSpider

isBug: false
isBio: false
isBuilding: true

experimental: false

constructionFootprint: -1, -1, 1, 1
footprint: -1, -1, 1, 1 

[graphics]
total_frames: 1
image: beamControlCenter.png
image_wreak: NONE
image_shadow: NONE



[movement]
movementType:BUILDING
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
targetHeight: 1
maxTurnSpeed: 0
turnAcceleration: 0

# essential emitter components

[attack]
canAttackLandUnits: true
canAttack: false
canAttackFlyingUnits: false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 999

maxAttackRange: 99999999
shootDelay: 0s

[turret_spawner]
x: 0
y: 0
canShoot: true
projectile: spawnBeamMobile
size: 0
shoot_flame: shockwave
limitingMinRange: 100

[projectile_spawnBeamMobile]
directDamage: 0
life: 100
speed: 8
drawSize: 0.8
instant: true
spawnUnit: basicOrbitalBeam_movable

[projectile_spawnBeamStatic]
directDamage: 0
life: 100
speed: 8
drawSize: 0.8
instant: true
spawnUnit: basicOrbitalBeam_static

# actions

[hiddenAction_cooldownOnSpawn]
addAllActionCooldownsTime: 60s
autoTriggerOnEvent: created

[action_strikeTargetMobile]
text: Set Target\n(Mobile Beam)
description: -Sets the target area where the mobile orbital beam will strike\n-Mobile Orbital Beam is steerable but weaker
fireTurretXAtGround: spawner
fireTurretXAtGround_withProjectile: spawnBeamMobile
price: 0
buildSpeed: 0s
allowMultipleInQueue: false
fireTurretXAtGround_showGuideDecals: beamPreview
addAllActionCooldownsTime: 60s
iconImage: beam.png

[decal_beamPreview]
image: beam.png
layer: inactive
teamColors: true


[action_strikeTargetStatic]
text: Set Target\n(Static Beam)
description: -Sets the target area where the static orbital beam will strike\n-Static Orbital Beam is not steerable but 3x stronger and larger
fireTurretXAtGround: spawner
fireTurretXAtGround_withProjectile: spawnBeamStatic
price: 0
buildSpeed: 0s
allowMultipleInQueue: false
fireTurretXAtGround_showGuideDecals: beamPreview2
addAllActionCooldownsTime: 60s
iconImage: beam.png

[decal_beamPreview2]
image: beam.png
layer: inactive
teamColors: true
imageScale: 3
