[core]
maxTransportingUnits: 5

[attachment_slot1]
x: 16
y: 16
canAttack: true
setDrawLayerOnBottom: true
addTransportedUnits: true

[attachment_slot2]
x: -16
y: 16
canAttack: true
setDrawLayerOnBottom: true
addTransportedUnits: true

[attachment_slot3]
x: 16
y: -16
canAttack: true
setDrawLayerOnBottom: true
addTransportedUnits: true

[attachment_slot4]
x: -16
y: -16
canAttack: true
setDrawLayerOnBottom: true
addTransportedUnits: true

[attachment_slot5]
x: 0
y: 0
canAttack: true
setDrawLayerOnBottom: true
addTransportedUnits: true

[core]
name: bunker2
tags: bunker2
displayText: Bunker (5 slots)
displayDescription: Holds units
class: CustomUnitMetadata
price: 750
maxHp: 750
mass: 9000

techLevel: 1
buildSpeed: 5
#availableInDemo: true


constructionFootprint: -1, -1, 1, 1
footprint: -1, -1, 1, 1
radius: 30

isBio: false
isBuilding: true

softCollisionOnAll: 5

explodeOnDeath: false


[graphics]
total_frames: 1

image: bunkerTop.png
image_back: bunker.png

image_wreak: NONE

#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: NONE



[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 0
maxAttackRange: 0
shootDelay: 0


[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0

maxTurnSpeed: 0
turnAcceleration: 0


[comment_action_spin]
setBodyRotation: 180
text: 180
price: 0
buildSpeed: 0


#[action_spin2]
setBodyRotation: 90
text: 90
price: 0
buildSpeed: 0


#[action_spin3]
setBodyRotation: 270
text: 270
price: 0
buildSpeed: 0





