
[core]
#autoTriggerCooldownTime: 0.5s
name: action_displayType_tut
displayText: Action Display Type sample
tags: wall
class: CustomUnitMetadata
price: 0
maxHp: 2000
mass: 9000
techLevel: 1
buildSpeed: 2s
radius: 15
isBio: false
isBuilding: true
#softCollisionOnAll: 5
footprint: 0,0,0,0

[graphics]
total_frames: 1
image: insulator.png
image_wreak: NONE
image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:2
drawLayer: ground

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 0
maxAttackRange: 100
shootDelay: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0

maxTurnSpeed: 0
turnAcceleration: 0


[template_actions]
text: ${type}
displayType: ${type}
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_label]
text: Display
displayType: infoOnly
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s


[action_label2]
text: Types
displayType: infoOnly
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_blank1]
text: %{" "}
displayType: infoOnlyNoBox
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_blank2]
text: %{" "}
displayType: infoOnlyNoBox
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s


[action_type_none]
@copyFromSection: template_actions
@define type: none

[action_type_rally]
@copyFromSection: template_actions
@define type: rally

[action_type_upgrade]
@copyFromSection: template_actions
@define type: upgrade

[action_type_queueUnit]
@copyFromSection: template_actions
@define type: queueUnit

[action_type_building]
@copyFromSection: template_actions
@define type: building

[action_type_action]
@copyFromSection: template_actions
@define type: action

[action_type_infoOnly]
@copyFromSection: template_actions
@define type: infoOnly

[action_type_infoOnlyNoBox]
@copyFromSection: template_actions
@define type: infoOnlyNoBox

[action_type_infoOnlyStockpile]
@copyFromSection: template_actions
@define type: infoOnlyStockpile

