
[core]
name: basicOrbitalBeam_static
displayText: Basic Static Orbital Beam
displayDescription: A demo for a simple and basic orbital beam that cannot be steered
class: CustomUnitMetadata
price: 1500
maxHp: 750
mass: 5000
techLevel: 1
isBio: false
buildSpeed: 25s
availableInDemo: true
radius: 50

ignoreInUnitCapCalculation: true
disableAllUnitCollisions: true
canNotBeGivenOrdersByPlayer: true

#this will prevent from being attacked and destroyed by conventional means
isUnselectableAsTarget: true
canNotBeDamaged: true
canNotBeDirectlyAttacked: true

energyMax: 4
energyRegen: -0.01
dieOnZeroEnergy: true


[graphics]
total_frames: 1
image:        SHARED:blank.png
image_wreak:   NONE
image_turret: NONE
image_shadow: AUTO
rotate_with_direction: false

[movement]
movementType: AIR
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
targetHeight: 1
targetHeightDrift: 0
maxTurnSpeed: 0
turnAcceleration: 0
moveIgnoringBody:true

#damage section

[core]
autoTriggerCooldownTime: 0.01s
autoTriggerCooldownTime_allowDangerousHighCPU: true

[attack]
canAttack: false

turretSize: 0
turretTurnSpeed: 1
maxAttackRange: 20
shootDelay:  0.0001s
aimOffsetSpread: 0

[hiddenAction_beamDamager]
autoTrigger: true
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 0, 0
#this will continously cast the splash damage
#every 0.00001s right at the center of the unit

[turret_1]
x: 0
y: 0
size: 0
shoot_light: #ffffff44

[projectile_1]
life: 40
targetGround: true
instant: true
deflectionPower: -1

directDamage: 0
areaDamage: 300
areaRadius: 200
areaDamageNoFalloff: true
friendlyFire: true
buildingDamageMultiplier: 3
areaHitAirAndLandAtSameTime: true

explodeEffect: CUSTOM:burn
lightColor: #ffffffff
lightSize: 70

[effect_burn]
priority: critical
image: scorch_mark_nuke.png
life: 2000
spawnChance: 0.1
attachedToUnit: false
scaleTo: 2.1
scaleFrom: 2.7
alpha: 0.4
dirOffsetRandom: 30
drawUnderUnits: true

# beam appearance


[decal_beam]
imageStack: beam.png*5000
imageScale: 0.9
stack_hOffset: 1
alpha: 0.3
layer: afterBody
hOffset: 500
order: 2
basePosition: createMarker(x=self.x, y=self.y, dir=self.timeAlive * -100)
teamColors: true

[decal_beam2]
imageStack: beam.png*500
imageScale: 1.5
stack_hOffset: 1
alpha: 0.25
layer: afterBody
order: 1
basePosition: createMarker(x=self.x, y=self.y, dir=self.timeAlive * 100)
teamColors: true

[decal_basePlate]
image: beam.png
imageScale: 3
layer: shadow
teamColors: true
basePosition: createMarker(x=self.x, y=self.y, dir=self.timeAlive * -50)