
[core]
#autoTriggerCooldownTime: 0.5s
name: action_icons_tut
displayText: Action Icons sample
tags: wall
class: CustomUnitMetadata
price: 0
maxHp: 2000
mass: 9000
techLevel: 1
buildSpeed: 2s
radius: 15
isBio: false
isBuilding: true
#softCollisionOnAll: 5
footprint: 0,0,0,0

[graphics]
total_frames: 1
image: insulator.png
image_wreak: NONE
image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:2
drawLayer: ground

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 0
maxAttackRange: 100
shootDelay: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0

maxTurnSpeed: 0
turnAcceleration: 0


[template_actions]
text: ${type}
displayType: ${type}
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_label]
text: Icon 
displayType: infoOnly
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s


[action_label2]
text: Sample
displayType: infoOnly
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_iconTest1]
text: %{" "}
description: iconImage  Only
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
iconImage: icon1.png


[action_iconTest2]
text: %{" "}
description: iconImage with iconExtraImage
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
iconImage: icon1.png
iconExtraImage: icon2.png

[action_iconTest3]
text: %{" "}
description: iconImage with red extra color
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
iconImage: icon1.png
iconExtraColor: #ff0000


[action_iconTest4]
text: %{" "}
description: iconImage with  iconExtraImage with red extra color
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
iconImage: icon1.png
iconExtraImage: icon2.png
iconExtraColor: #ff0000

[action_blank1]
text: %{" "}
displayType: infoOnlyNoBox
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_blank2]
text: %{" "}
displayType: infoOnlyNoBox
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_label3]
text: Unit Icon 
displayType: infoOnly
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s


[action_label4]
text: Sample
displayType: infoOnly
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s

[action_uniticonTest1]
text: %{" "}
description: unitShownInUI
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
#iconImage: icon1.png
unitShownInUI:  unitref self.nearestUnit(withTag="basicTank")
unitShownInUIWithHpBar: false
unitShownInUIWithProgressBar: false

[action_uniticonTest2]
text: %{" "}
description: unitShownInUI\n with iconExtraImage
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
#iconImage: icon1.png
unitShownInUI:  unitref self.nearestUnit(withTag="basicTank")
iconExtraImage: icon2.png
unitShownInUIWithHpBar: false
unitShownInUIWithProgressBar: false

[action_uniticonTest4]
text: %{" "}
description: unitShownInUI\n with red extra color
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
#iconImage: icon1.png
unitShownInUI: unitref self.nearestUnit(withTag="basicTank")
iconExtraColor: #ff0000
unitShownInUIWithHpBar: false
unitShownInUIWithProgressBar: false

[action_uniticonTest5]
text: %{" "}
description: unitShownInUI\n with iconExtraImage with red extra color
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
#iconImage: icon1.png
unitShownInUI: unitref self.nearestUnit(withTag="basicTank")
iconExtraImage: icon2.png
iconExtraColor: #ff0000
unitShownInUIWithHpBar: false
unitShownInUIWithProgressBar: false

[action_uniticonTest6]
text: %{" "}
description: unitShownInUI\n with HP
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
#iconImage: icon1.png
unitShownInUI:  unitref self.nearestUnit(withTag="basicTank")
unitShownInUIWithHpBar: true
unitShownInUIWithProgressBar: false

[action_uniticonTest7]
text: %{" "}
description: unitShownInUI \n with Progress Bar
price: 0
allowMultipleInQueue: false
addResources: hp = 1
buildSpeed: 0s
#iconImage: icon1.png
unitShownInUI:  unitref self.nearestUnit(withTag="basicTank")
unitShownInUIWithProgressBar: true
unitShownInUIWithHpBar: false